checkpoint:
  path: /mount/arbeitsdaten54/projekte/deepfake/SpeechTechnology2023/chihyi/deepfake-whisper-softmax/deepfake-whisper-features/trained_models/model__whisper_frontend_mesonet__1712814576.3199446/ckpt.pth
data:
  seed: 42
model:
  name: whisper_frontend_mesonet
  optimizer:
    lr: 1.0e-06
    weight_decay: 0.0001
  parameters:
    fc1_dim: 1024
    freeze_encoder: false
    frontend_algorithm:
    - mfcc
    input_channels: 2
